### ISSUE TITLE
group names which contain a comma

### ISSUE THREAD

**Issue by HenrikBernhard** [microsoft/nmarc#5]
As we have a number of groups which contain a comma in their name, the generated CSV file fails to import correctly to excel 

would it be possible to change the delimiter to another value - or even better enclose the values in "" so excel can import/break columns correctly
would work
"3479542","Name of,Department","internal","unlisted","active","7","2/2/2018 2:09:15" 

splits one value into two columns and messes up format in excel
3479542,Name of,Department,internal,unlisted,active,7,2/2/2018 2:09:15

**Comment by Narobix** [comment]
Oh I had this too but got around it - do a find replace on the yaml file in your notepad++ or similar tool.
Replace    ,    With a unique string you can easily replace later - I used COMMA for irony.

**Comment by brianly** [comment]
The CSV output is really naive in the current implementation. I'm updating this to something better. Arguably changing to tab-separated output might be better since these fields might have arbitrary characters. I hope to fix the encoding issues at the same time.

**Comment by brianly** [comment]
This was fixed in #20 which adds the ability to have a custom separator.
